version: "3.8"
services:
  pg:
    image: postgres
    networks:
      - rails
    volumes:
      - log:/var/log
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis
    networks:
      - rails
    volumes:
      - log:/var/log

  web:
    build: . 
    command: rails s -b 0.0.0.0
    networks:
      - rails
    depends_on:
      - redis
      - pg
    ports:
      - 3000:3000
    volumes:
      - .:/application
      - log:/application/log
      - log:/var/log

volumes:
  log:
  pg_data:

networks:
  rails:
